"""User and role models for Rally Safety App."""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class UserRole(str, Enum):
    """9 user roles in the system."""
    VEDOUCI = "vedouci"                    # Head of RZ
    ZASTUPCE = "zastupce"                  # Deputy head
    KOMISAR_TRAT = "komisar_trat"          # Track marshal
    KOMISAR_ZATACKA = "komisar_zatacka"    # Corner marshal
    CASOMER = "casomer"                    # Timekeeper
    PARKOVANI = "parkovani"                # Parking marshal
    ZDRAVOTNIK = "zdravotnik"              # Medical personnel
    TECHNIK = "technik"                    # Technical support
    ADMIN = "admin"                        # System administrator


class User(BaseModel):
    """User model - represents both vedení and komisaři."""
    user_id: str = Field(..., description="Unique user ID")
    name: str = Field(..., min_length=1, max_length=100)
    role: UserRole
    station_id: Optional[str] = Field(None, description="Assigned station ID")
    pin_code: Optional[str] = Field(None, description="4-digit PIN for komisaři")
    phone: Optional[str] = Field(None, description="Phone number (optional)")
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "user_id": "user_001",
                "name": "Jan Novák",
                "role": "komisar_trat",
                "station_id": "TK-01",
                "pin_code": "1234",
                "phone": "+420123456789"
            }
        }
    )


class KomisarAccess(BaseModel):
    """Komisař access credentials - generated by vedení."""
    pin_code: str = Field(..., min_length=4, max_length=4, pattern=r"^\d{4}$")
    name: str = Field(..., min_length=1, max_length=100)
    role: UserRole
    phone: Optional[str] = None
    station_id: Optional[str] = None
    created_at: Optional[str] = None
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "pin_code": "1234",
                "name": "Jan Novák",
                "role": "komisar_trat",
                "phone": "+420123456789",
                "station_id": "TK-01"
            }
        }
    )


# Hardcoded vedení credentials for MVP (in real app, this would be in database)
VEDENI_CREDENTIALS = {
    "admin": {
        "password_hash": "$2b$12$/Hja06MPyPq3bnBF64VusuQ5OdzvYzduaqUCXWCXfqe1wGQkIwby6",  # "demo123"
        "name": "Vedoucí RZ",
        "role": UserRole.VEDOUCI,
        "phone": "+420777123456",
    }
}
